"use client";
import { AlertTriangle, Scale, Shield, FileWarning } from "lucide-react";
import PageWrapper from "@/components/layout/PageWrapper";
import { PageHeader } from "@/components/ui/PageHeader";
import { Badge } from "@/components/ui/Badge";

export default function TermsOfServicePage() {
  return (
    <PageWrapper>
      <PageHeader
        title="Terms of Service"
        subtitle="Legal terms governing the use of Uhasibu Digito™"
        breadcrumbs={[{ label: "Legal" }, { label: "Terms of Service" }]}
      />

      <div className="mb-6 flex items-start gap-3 p-4 rounded-2xl border border-ud-warning/30 bg-ud-warning-bg">
        <AlertTriangle className="w-5 h-5 text-ud-warning flex-shrink-0 mt-0.5" />
        <div className="text-sm text-ud-text-secondary leading-relaxed">
          <Badge variant="warning" size="sm" className="mb-1">Demo terms</Badge>
          <p>
            This is demo-grade legal copy intended to illustrate the contractual posture of the platform.
            <span className="font-semibold text-ud-text-primary"> Final wording must be reviewed and approved by a Tanzanian-qualified lawyer</span>{" "}
            before production deployment. Do not rely on this text as enforceable legal terms.
          </p>
        </div>
      </div>

      <article className="space-y-6">
        <Section icon={<Scale className="w-5 h-5" />} title="1. Acceptance of terms">
          <p>
            By accessing or using Uhasibu Digito™ ("the Platform"), you agree to be bound by these Terms of
            Service. If you do not agree, you may not use the Platform. These terms govern the relationship
            between you ("User", "Client") and the Platform operators ("we", "us").
          </p>
        </Section>

        <Section icon={<Shield className="w-5 h-5" />} title="2. Limitation of liability & contributory negligence">
          <p>
            Uhasibu Digito™ provides accounting, bookkeeping, payroll, tax-preparation, and management-reporting
            tools. The accuracy of figures, descriptions, and classifications entered into the Platform is the{" "}
            <span className="font-semibold text-ud-text-primary">sole responsibility of the User</span>.
          </p>
          <p>
            If a User over-reports or under-reports any financial value, tax position, statutory return, asset
            valuation, or any other figure — whether by error, omission, misclassification, miscalculation, or
            otherwise — Uhasibu Digito™, its operators, employees, contractors, licensors, and affiliates accept{" "}
            <span className="font-semibold text-ud-text-primary">no liability</span> whatsoever for any resulting
            consequences, including but not limited to: penalties, fines, interest, prosecution, civil claims,
            reputational damage, loss of contracts, or loss of business.
          </p>
          <p>
            Users are advised to engage a qualified accountant and tax advisor and to{" "}
            <span className="font-semibold text-ud-text-primary">independently verify all outputs</span> before
            submission to the Tanzania Revenue Authority (TRA), the National Board of Accountants and Auditors
            (NBAA), the National Social Security Fund (NSSF), the Workers&apos; Compensation Fund (WCF), the Higher
            Education Students&apos; Loans Board (HESLB), or any third party.
          </p>
        </Section>

        <Section icon={<FileWarning className="w-5 h-5" />} title="3. No professional advice">
          <p>
            Outputs generated by the Platform — including financial statements, tax computations, depreciation
            schedules, payroll calculations, and AI-assistant responses — are{" "}
            <span className="font-semibold text-ud-text-primary">not</span> professional accounting, tax, legal,
            or financial advice. The Platform is a tool; it does not replace a qualified accountant, auditor, or
            tax advisor.
          </p>
        </Section>

        <Section title="4. Intellectual property" id="nbaa">
          <p>
            <span className="font-semibold text-ud-text-primary">Uhasibu Digito™</span> is a trademark of the
            Platform operators. The Platform&apos;s source code, design, brand mark, name, logo, copy, and all
            related materials are protected by copyright and trademark law. You may not copy, reproduce, rebrand,
            resell, or reverse-engineer the Platform or any substantial part of it without express written
            permission. Any unauthorised duplication — including republishing under a different name — is a
            breach of these terms and applicable intellectual-property law.
          </p>
        </Section>

        <Section title="5. Compliance posture">
          <p>
            The Platform&apos;s financial outputs are designed to be consistent with{" "}
            <span className="font-semibold text-ud-text-primary">International Financial Reporting Standards
            (IFRS)</span>, <span className="font-semibold text-ud-text-primary">International Accounting
            Standards (IAS)</span>, <span className="font-semibold text-ud-text-primary">IFRS for SMEs</span>,
            and the <span className="font-semibold text-ud-text-primary">Tanzania Financial Reporting Standards
            (TFRS)</span>, in line with the disclosure requirements of the National Board of Accountants and
            Auditors (NBAA) of Tanzania. Final responsibility for compliance rests with the User and their
            engaged professionals.
          </p>
        </Section>

        <Section title="6. Privacy" id="privacy">
          <p>
            We process data you enter solely for the purpose of providing the Platform&apos;s services. We do not
            sell your data. A full privacy notice will be published prior to general availability and will be
            reviewed by Tanzanian counsel for compliance with the Personal Data Protection Act, 2022.
          </p>
        </Section>

        <Section title="7. Changes to these terms">
          <p>
            We may update these terms from time to time. Material changes will be communicated through the
            Platform. Continued use after such notice constitutes acceptance of the updated terms.
          </p>
        </Section>

        <Section title="8. Governing law">
          <p>
            These terms are governed by the laws of the United Republic of Tanzania. Any dispute shall be
            referred to the courts of Tanzania having appropriate jurisdiction.
          </p>
        </Section>
      </article>
    </PageWrapper>
  );
}

function Section({ icon, title, id, children }: { icon?: React.ReactNode; title: string; id?: string; children: React.ReactNode }) {
  return (
    <section id={id} className="bg-white border border-ud-border rounded-2xl p-6 shadow-card scroll-mt-20">
      <h2 className="font-display font-bold text-base text-ud-text-primary mb-3 flex items-center gap-2">
        {icon && <span className="text-ud-primary">{icon}</span>}
        {title}
      </h2>
      <div className="space-y-3 text-sm text-ud-text-secondary leading-relaxed">{children}</div>
    </section>
  );
}
